apiVersion: "v1"
kind: Pod
metadata:
  name: calcfrontend
  labels:
    name: calcfrontend
    app: calculator
spec:
  containers:
    - name: calcfrontend
      image: sterilizefleshedbonelike.azurecr.io/js-calc-frontend:v2
      ports:
        - containerPort: 8080
          name: calcfrontend
          protocol: TCP
      env:
        - name: "ENDPOINT"
          value: "calcbackendsvc"
        - name: "PORT"
          value: "8080"
